package com.naammm.trickcode.service.export;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.naammm.trickcode.service.InstructorDashboardService;
import com.naammm.trickcode.service.dto.InstructorDashboardStatsDTO;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

/**
 * Service for exporting Instructor dashboard data to PDF.
 */
@Service
public class InstructorPdfExportService {

    private static final Font TITLE_FONT = new Font(Font.HELVETICA, 20, Font.BOLD, new Color(30, 30, 30));
    private static final Font SUBTITLE_FONT = new Font(Font.HELVETICA, 10, Font.NORMAL, new Color(120, 120, 120));
    private static final Font SECTION_FONT = new Font(Font.HELVETICA, 14, Font.BOLD, new Color(30, 30, 30));
    private static final Font HEADER_FONT = new Font(Font.HELVETICA, 9, Font.BOLD, Color.WHITE);
    private static final Font CELL_FONT = new Font(Font.HELVETICA, 9, Font.NORMAL, new Color(50, 50, 50));
    private static final Font METRIC_LABEL = new Font(Font.HELVETICA, 9, Font.NORMAL, new Color(100, 100, 100));
    private static final Font METRIC_VALUE = new Font(Font.HELVETICA, 18, Font.BOLD, new Color(30, 30, 30));

    private static final Color HEADER_BG = new Color(38, 38, 38);
    private static final Color STRIPE_BG = new Color(248, 248, 248);

    private final InstructorDashboardService instructorDashboardService;

    public InstructorPdfExportService(InstructorDashboardService instructorDashboardService) {
        this.instructorDashboardService = instructorDashboardService;
    }

    public byte[] exportToPdf() throws IOException {
        InstructorDashboardStatsDTO stats = instructorDashboardService.getStats();
        String login = SecurityContextHolder.getContext().getAuthentication().getName();

        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4, 40, 40, 40, 40);
            PdfWriter.getInstance(document, out);
            document.open();

            // Title
            Paragraph title = new Paragraph("Course Overview Report", TITLE_FONT);
            title.setSpacingAfter(4);
            document.add(title);

            Paragraph sub = new Paragraph(
                "Instructor: " + login + "  |  Generated: " + LocalDate.now().format(DateTimeFormatter.ISO_LOCAL_DATE),
                SUBTITLE_FONT
            );
            sub.setSpacingAfter(20);
            document.add(sub);

            // Add separator line
            document.add(createSeparator());

            // Key Metrics
            document.add(createSectionTitle("Key Metrics"));
            document.add(createMetricsTable(stats));

            document.add(new Paragraph("\n"));
            document.add(createSeparator());

            // Course Performance Table
            document.add(createSectionTitle("Course Performance"));

            if (stats.getCourseStats() != null && !stats.getCourseStats().isEmpty()) {
                document.add(createCourseTable(stats));
            } else {
                document.add(new Paragraph("No courses found.", CELL_FONT));
            }

            document.add(new Paragraph("\n"));
            document.add(createSeparator());

            // Recent Enrollments
            document.add(createSectionTitle("Recent Enrollments"));

            if (stats.getRecentEnrollments() != null && !stats.getRecentEnrollments().isEmpty()) {
                document.add(createEnrollmentTable(stats));
            } else {
                document.add(new Paragraph("No recent enrollments.", CELL_FONT));
            }

            // Footer
            document.add(new Paragraph("\n\n"));
            Paragraph footer = new Paragraph(
                "This report was generated by TrickCode Platform. All monetary values are in USD.",
                SUBTITLE_FONT
            );
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
            return out.toByteArray();
        } catch (DocumentException e) {
            throw new IOException("Failed to generate PDF: " + e.getMessage(), e);
        }
    }

    private Element createSeparator() {
        PdfPTable line = new PdfPTable(1);
        line.setWidthPercentage(100);
        PdfPCell cell = new PdfPCell();
        cell.setBorderWidth(0);
        cell.setBorderWidthBottom(0.5f);
        cell.setBorderColorBottom(new Color(220, 220, 220));
        cell.setFixedHeight(1);
        cell.setPaddingBottom(10);
        line.addCell(cell);
        line.setSpacingAfter(15);
        return line;
    }

    private Element createSectionTitle(String text) {
        Paragraph p = new Paragraph(text, SECTION_FONT);
        p.setSpacingBefore(5);
        p.setSpacingAfter(12);
        return p;
    }

    private PdfPTable createMetricsTable(InstructorDashboardStatsDTO stats) {
        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        table.setSpacingAfter(10);

        addMetricCell(table, "Total Courses", String.valueOf(stats.getTotalCourses()));
        addMetricCell(table, "Published", String.valueOf(stats.getPublishedCourses()));
        addMetricCell(table, "Total Enrollments", String.valueOf(stats.getTotalStudents()));
        addMetricCell(table, "Net Earnings",
            "$" + (stats.getTotalRevenue() != null ? String.format("%.2f", stats.getTotalRevenue()) : "0.00"));

        return table;
    }

    private void addMetricCell(PdfPTable table, String label, String value) {
        PdfPCell cell = new PdfPCell();
        cell.setBorderWidth(0.5f);
        cell.setBorderColor(new Color(230, 230, 230));
        cell.setPadding(12);
        cell.setBackgroundColor(new Color(252, 252, 252));

        Paragraph labelP = new Paragraph(label, METRIC_LABEL);
        labelP.setSpacingAfter(4);
        cell.addElement(labelP);
        cell.addElement(new Paragraph(value, METRIC_VALUE));

        table.addCell(cell);
    }

    private PdfPTable createCourseTable(InstructorDashboardStatsDTO stats) {
        PdfPTable table = new PdfPTable(new float[]{3.5f, 1.2f, 1.2f, 1f, 1.2f, 1.5f});
        table.setWidthPercentage(100);
        table.setSpacingAfter(10);

        addTableHeader(table, "Course Title");
        addTableHeader(table, "Status");
        addTableHeader(table, "Level");
        addTableHeader(table, "Price");
        addTableHeader(table, "Students");
        addTableHeader(table, "Earnings");

        int row = 0;
        for (InstructorDashboardStatsDTO.CourseStatDTO cs : stats.getCourseStats()) {
            Color bg = (row % 2 == 0) ? Color.WHITE : STRIPE_BG;
            addTableCell(table, cs.getCourseTitle(), bg);
            addTableCell(table, cs.getStatus(), bg);
            addTableCell(table, cs.getLevel() != null ? cs.getLevel() : "—", bg);
            addTableCell(table, cs.getPrice() != null && cs.getPrice().compareTo(BigDecimal.ZERO) > 0
                ? "$" + cs.getPrice() : "Free", bg);
            addTableCell(table, String.valueOf(cs.getEnrollmentCount()), bg);
            addTableCell(table, cs.getRevenue() != null ? "$" + String.format("%.2f", cs.getRevenue()) : "$0.00", bg);
            row++;
        }

        return table;
    }

    private PdfPTable createEnrollmentTable(InstructorDashboardStatsDTO stats) {
        PdfPTable table = new PdfPTable(new float[]{2f, 3f, 3f, 2f});
        table.setWidthPercentage(100);
        table.setSpacingAfter(10);

        addTableHeader(table, "Student");
        addTableHeader(table, "Email");
        addTableHeader(table, "Course");
        addTableHeader(table, "Date");

        int row = 0;
        for (InstructorDashboardStatsDTO.RecentEnrollmentDTO e : stats.getRecentEnrollments()) {
            Color bg = (row % 2 == 0) ? Color.WHITE : STRIPE_BG;
            addTableCell(table, e.getUserLogin(), bg);
            addTableCell(table, e.getUserEmail(), bg);
            addTableCell(table, e.getCourseTitle(), bg);
            addTableCell(table, e.getEnrolledAt() != null
                ? LocalDate.ofInstant(e.getEnrolledAt(), java.time.ZoneId.systemDefault()).format(DateTimeFormatter.ISO_LOCAL_DATE)
                : "—", bg);
            row++;
        }

        return table;
    }

    // --- Table Helpers ---

    private void addTableHeader(PdfPTable table, String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, HEADER_FONT));
        cell.setBackgroundColor(HEADER_BG);
        cell.setPadding(8);
        cell.setBorderWidth(0);
        cell.setPaddingBottom(10);
        table.addCell(cell);
    }

    private void addTableCell(PdfPTable table, String text, Color bg) {
        PdfPCell cell = new PdfPCell(new Phrase(text, CELL_FONT));
        cell.setBackgroundColor(bg);
        cell.setPadding(7);
        cell.setBorderWidth(0);
        cell.setBorderWidthBottom(0.3f);
        cell.setBorderColorBottom(new Color(235, 235, 235));
        table.addCell(cell);
    }
}
