package com.naammm.course.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LessonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLessonAllPropertiesEquals(Lesson expected, Lesson actual) {
        assertLessonAutoGeneratedPropertiesEquals(expected, actual);
        assertLessonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLessonAllUpdatablePropertiesEquals(Lesson expected, Lesson actual) {
        assertLessonUpdatableFieldsEquals(expected, actual);
        assertLessonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLessonAutoGeneratedPropertiesEquals(Lesson expected, Lesson actual) {
        assertThat(actual)
            .as("Verify Lesson auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLessonUpdatableFieldsEquals(Lesson expected, Lesson actual) {
        assertThat(actual)
            .as("Verify Lesson relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getOrderIndex()).as("check orderIndex").isEqualTo(expected.getOrderIndex()))
            .satisfies(a -> assertThat(a.getDurationSeconds()).as("check durationSeconds").isEqualTo(expected.getDurationSeconds()))
            .satisfies(a -> assertThat(a.getIsPreview()).as("check isPreview").isEqualTo(expected.getIsPreview()))
            .satisfies(a -> assertThat(a.getVideoUrl()).as("check videoUrl").isEqualTo(expected.getVideoUrl()))
            .satisfies(a -> assertThat(a.getCaptionUrl()).as("check captionUrl").isEqualTo(expected.getCaptionUrl()))
            .satisfies(a -> assertThat(a.getMarkdownContent()).as("check markdownContent").isEqualTo(expected.getMarkdownContent()))
            .satisfies(a -> assertThat(a.getQuizConfig()).as("check quizConfig").isEqualTo(expected.getQuizConfig()))
            .satisfies(a ->
                assertThat(a.getCodeChallengeConfig()).as("check codeChallengeConfig").isEqualTo(expected.getCodeChallengeConfig())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLessonUpdatableRelationshipsEquals(Lesson expected, Lesson actual) {
        assertThat(actual)
            .as("Verify Lesson relationships")
            .satisfies(a -> assertThat(a.getSection()).as("check section").isEqualTo(expected.getSection()));
    }
}
