package com.naammm.trickcode.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSectionAllPropertiesEquals(Section expected, Section actual) {
        assertSectionAutoGeneratedPropertiesEquals(expected, actual);
        assertSectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSectionAllUpdatablePropertiesEquals(Section expected, Section actual) {
        assertSectionUpdatableFieldsEquals(expected, actual);
        assertSectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSectionAutoGeneratedPropertiesEquals(Section expected, Section actual) {
        assertThat(actual)
            .as("Verify Section auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSectionUpdatableFieldsEquals(Section expected, Section actual) {
        assertThat(actual)
            .as("Verify Section relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getOrderIndex()).as("check orderIndex").isEqualTo(expected.getOrderIndex()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSectionUpdatableRelationshipsEquals(Section expected, Section actual) {
        assertThat(actual)
            .as("Verify Section relationships")
            .satisfies(a -> assertThat(a.getCourse()).as("check course").isEqualTo(expected.getCourse()));
    }
}
